#!/usr/bin/env bash
# debugging nginx port 80 
# NB: The flag -s creates a symbolic link, -f deletes the existing file and replaces it

sudo ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
